version: "3.7"

services:

  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: symfony-api
    volumes:
      - ./:/app

  nginx:
    image: nginx:latest
    ports:
      - 8800:80
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    restart: always
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

volumes:
  postgres-data:
